package com.exception.handling.practice;

class parent extends Exception{
	public void m1() {
		
	}
}
public class ExceptionHandlingDemo {
	public static void main(String[] args) {
		try {
			int n = 10 / 0;
			System.out.println(n);
			System.exit(0);
		} catch (ArithmeticException e) {
			System.out.println("Catch exception handled");
			System.exit(0);
		}
		finally {
			System.out.println("finally block executed");
		}

	}

}
